version: '3'
services:
    flyway-migrate:
        image: flyway/flyway
        command: -url=jdbc:postgresql://postgres:5432/store_sales_db -schemas=app -user=root -password=root -connectRetries=10 -baselineOnMigrate="false" migrate
        volumes:
            - ./src/main/resources/db/migration:/flyway/sql
        depends_on:
            - flyway-clean

    flyway-clean:
        image: flyway/flyway
        command: -url=jdbc:postgresql://postgres:5432/store_sales_db -schemas=app -user=root -password=root -connectRetries=10 -cleanDisabled="false" clean
        volumes:
            - ./src/main/resources/db/migration:/flyway/sql
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine3.17
        restart: unless-stopped
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=store_sales_db
